name: Angular Workflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Angular Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm i

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test -- --no-watch --no-progress --browsers=AngularElectron

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura-coverage.xml

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Build Code
        run: npm run build
