name: Angular Workflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build Code
        run: npm run build
