name: Release Virus Total Scan

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: windows-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@octokit-retry
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            *.exe
